mysite/assessment/urls.py
from django.urls import path, re_path
from assessment.views import *

app_name = 'assessment'


urlpatterns = [
path('', PostLV.as_view(), name='index'),
# re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),
path('<int:pk>/', PostDV.as_view(), name='detail'),
]

mysite/blog/urls.py
from django.urls import path, re_path
from blog.views import *
from blog import views


app_name = 'blog'
urlpatterns = [
    path('', PostLV.as_view(), name='index'),

    path('<int:pk>/',PostDV.as_view(), name='detail'),
    #re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),

    #Example : /blog/archive/
    path('archive/', PostAV.as_view(), name='post_archive'),
    
    # Example: /blog/archive/2019/
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    
    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    
    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # Example : /blog/add/
    path('add/', PostCreateView.as_view(), name ='add'),

    # Example :/blog/99/update/
    path('<int:pk>/update/', PostUpdateView.as_view(), name ="update"),

    # Example :/blog/99/delete/
    path('<int:pk>/delete/', PostDeleteView.as_view(), name ="delete"),

    # Example :
    path('download/<int:id>', download, name="download"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import  HomeView, UserCreateView, UserCreateDoneTV
from django.urls import path

# from instrouction.views import InstrouctionLV, InstrouctionDV
from mysite.views import HomeView, InstrouctionIntroView, InstrouctionPlanView, InstrouctionStructureView, InstrouctionView, ProfileView

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='home'),
    path('account/', include('django.contrib.auth.urls')), # 로그인, 로그아웃, 비밀번호 변경 등 담당
    
    
    path('account/register/', UserCreateView.as_view(), name='register'), 
    path('account/register/done/', UserCreateDoneTV.as_view(),name='register_done'), # 회원 가입 및 처리
    path('instrouction/',InstrouctionView.as_view(), name='instrouctionbase'),
    path('instrouction/intro',InstrouctionIntroView.as_view(), name ='intro'),
    path('instrouction/structure',InstrouctionStructureView.as_view(), name ='structure'),
    path('instrouction/plan',InstrouctionPlanView.as_view(), name ='plan'),
    path('assessment/', include('assessment.urls')), #평가 url
    path('instrouction/',include('instrouction.urls')),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('blog/',include('blog.urls')),
    path('board/', include('board.urls')),
    path('events/',include('events.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

mysite/assessment/models.py
from django.db import models
from django.urls import reverse
from account.models import User      # add.  -> commit -> pull 

# User.interface_set.all  
# User.interface_project_set.all

class Interface(models.Model):
    #  Foeign Key 설정, on_delete 설정 : 참조한 키가 삭제되면 그 키와 관련된 데이터를 같이 삭제해주세요
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    performance = models.IntegerField(null=True)
    performance_re = models.IntegerField(null=True)
    writing = models.IntegerField(null=True)
    writing_re= models.IntegerField(null=True)
    attitude =  models.IntegerField(null=True)
    Portfolio = models.IntegerField(null=True)

    class Meta:
        verbose_name = 'interface'
        db_table = 'assessment_interface' # 테이블명 재정의
    
class Interface_project(models.Model):
    #  Foeign Key 설정, on_delete 설정 : 참조한 키가 삭제되면 그 키와 관련된 데이터를 같이 삭제해주세요
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    performance = models.IntegerField(null=True)
    performance_re = models.IntegerField(null=True)
    writing = models.IntegerField(null=True)
    writing_re= models.IntegerField(null=True)
    attitude =  models.IntegerField(null=True)
    Portfolio = models.IntegerField(null=True)

    class Meta:
        verbose_name = 'interface_project'
        db_table = 'assessment_interface_project' # 테이블명 재정의

class edge_device(models.Model):
    #  Foeign Key 설정, on_delete 설정 : 참조한 키가 삭제되면 그 키와 관련된 데이터를 같이 삭제해주세요
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    performance = models.IntegerField(null=True)
    performance_re = models.IntegerField(null=True)
    writing = models.IntegerField(null=True)
    writing_re= models.IntegerField(null=True)
    attitude =  models.IntegerField(null=True)
    Portfolio = models.IntegerField(null=True)

    class Meta:
        verbose_name = 'edge_device'
        db_table = 'assessment_edge_device' # 테이블명 재정의

class gateway_device(models.Model):
    #  Foeign Key 설정, on_delete 설정 : 참조한 키가 삭제되면 그 키와 관련된 데이터를 같이 삭제해주세요
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    performance = models.IntegerField(null=True)
    performance_re = models.IntegerField(null=True)
    writing = models.IntegerField(null=True)
    writing_re= models.IntegerField(null=True)
    attitude =  models.IntegerField(null=True)
    Portfolio = models.IntegerField(null=True)

    class Meta:
        verbose_name = 'gateway_device'
        db_table = 'assessment_gateway_device' # 테이블명 재정의

class iot_project(models.Model):
    #  Foeign Key 설정, on_delete 설정 : 참조한 키가 삭제되면 그 키와 관련된 데이터를 같이 삭제해주세요
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    performance = models.IntegerField(null=True)
    performance_re = models.IntegerField(null=True)
    writing = models.IntegerField(null=True)
    writing_re= models.IntegerField(null=True)
    attitude =  models.IntegerField(null=True)
    Portfolio = models.IntegerField(null=True)

    class Meta:
        verbose_name = 'iot_project'
        db_table = 'assessment_iot_project' # 테이블명 재정의

class mix_project(models.Model):
    #  Foeign Key 설정, on_delete 설정 : 참조한 키가 삭제되면 그 키와 관련된 데이터를 같이 삭제해주세요
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    performance = models.IntegerField(null=True)
    performance_re = models.IntegerField(null=True)
    writing = models.IntegerField(null=True)
    writing_re= models.IntegerField(null=True)
    attitude =  models.IntegerField(null=True)
    Portfolio = models.IntegerField(null=True)

    class Meta:
        verbose_name = 'mix_project'
        db_table = 'assessment_mix_project' # 테이블명 재정의




class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    # slug = models.SlugField('SLUG', unique=True, allow_unicode=True,help_text='one word for title alias.')
    performance = models.IntegerField(null=True)
    performance_re = models.IntegerField(null=True)
    writing = models.IntegerField(null=True)
    writing_re= models.IntegerField(null=True)
    attitude =  models.IntegerField(null=True)
    Portfolio = models.IntegerField(null=True)
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)


    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'assessment_posts' # 테이블명 재정의
        ordering = ('-modify_dt',) # orderby 절, -이면 내림차순

    def __str__(self):
        return self.title
    # def get_absolute_url(self): # 현재 데이터의 절대 경로 추출
    # return  reverse('assessment:post_detail', args=(self.slug,))
    def get_previous(self): # 이전 데이터 추출
        return self.get_previous_by_modify_dt()
    def get_next(self): # 다음 데이터 추출
        return self.get_next_by_modify_dt()

mysite/assessment/views.py
from django.views.generic import ListView, DetailView
from assessment.models import Interface_project, Post ,Interface
from account.models import User


# ListView
class PostLV(ListView):
    model = Post
    template_name = 'assessment/post_all.html' # 템플릿 파일명 변경
    context_object_name = 'posts' # 컨텍스트 객체 이름 변경(object_list)
#  paginate_by = 6 # 페이지네이션, 페이지당 문서 건 수    
    def get_context_data(self, **kwargs) :
        context= super().get_context_data(**kwargs)
        context['object_list']=Interface.objects.all()
        return context



    def get_context_data_pro(self, **kwargs) :
        context= super().get_context_data(**kwargs)
        context['object_list']=Interface_project.objects.all()
        return context

#  class InstrouctionDV(DetailView):
#     model = Instrouction
#     ## defatul : templates/app_name/model_detail
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs) # object 만들어낸다.
#         context['object_list'] = Instrouction.objects.all()
#         return context


# DetailView
class PostDV(DetailView):
    model = Post

mysite/assessment/templates/assessment/post_all.html
{% extends "base.html" %}

 {% block content %}
<style>


    
    table{
        position : relative;
        top : 50px;
        left : 100px;
        

 }    

    .pointer{
        color:blue;
        font-weight:bold;
        text-align:left;    
    }

    th,td {
        color: #0d47a1;
        font-size: 16px;
        text-align : center;
        

    }

    .btn-success{
        background-color: #00c851!important;
        float:right;
    }
    
    .highlight{
        position:relative;
        left: 100px;
        color:#0d47a1;
        font-size : 30px;
        
    }

</style>



<div class="card" style="height:500px;margin-left:20px;">  
    <br>
<div class="highlight">
<i class="fas fa-highlighter"> 성취도 평가</i>
</div>
    <body>        
        <div class="table"><table border="0" style="width:80%"> <tr><th>비NCS 교과명</th> <th>수행1</th><th>수행2</th><th>필답1</th><th>필답2</th><th>태도</th><th>포트폴리오</th> </tr>
        <td div class= "pointer"> <i class="fas fa-chalkboard-teacher"></i> 인터페이스 개발 </td>
         {% for interface in user.interface_set.all %}
         <td>{{interface.performance}}</td> <td>{{interface.performance_re}}</td><td>{{interface.writing}}</td><td>{{interface.writing_re}}</td><td>{{interface.attitude}}</td><td>{{interface.Portfolio}}</td>
         {% endfor %}
         <tr>   
            <td div class="pointer"><i class="fas fa-chalkboard-teacher"></i>  인터페이스 개발 프로젝트 <button type="button" class="btn btn-success">포트폴리오</button>
            </td>{% for interpro in user.interface_project_set.all %}
            <td>{{interpro.performance}}</td> <td>{{interpro.performance_re}}</td><td>{{interpro.writing}}</td><td>{{interpro.writing_re}}</td><td>{{interpro.attitude}}</td><td>{{interpro.Portfolio}}</td>
            {% endfor %}
         </tr>
         <tr>
            <td div class= "pointer"> <i class="fas fa-chalkboard-teacher"></i> 엣지 디바이스 제어</td>
            {% for edge in user.edge_device_set.all %}
            <td>{{edge.performance}}</td> <td>{{edge.performance_re}}</td> <td>{{edge.writing}}</td> <td>{{edge.writing_re}}</td> <td>{{edge.attitude}}</td> <td>{{edge.Portfolio}}</td>
            {% endfor %}
         </tr>   
         <tr>
             <td div class="pointer"> <i class="fas fa-chalkboard-teacher"></i> 게이트 웨이 디바이스 제어</td>
             {% for gateway in user.gateway_device_set.all %}
             <td>{{gateway.performance}}</td> <td>{{gateway.performance_re}}</td> <td>{{gateway.writing}}</td> <td>{{gateway.writing_re}}</td> <td>{{gateway.attitude}}</td> <td>{{gateway.Portfolio}}</td>
             {% endfor %}
         </tr> 
         <tr>
             <td div class="pointer"> <i class="fas fa-chalkboard-teacher"></i> Iot 프로젝트 <button type="button" class="btn btn-success">포트폴리오</button>
             </td>
             {% for iot in user.iot_project_set.all %}
             <td>{{iot.performance}}</td> <td>{{iot.performance_re}}</td> <td>{{iot.writing}}</td> <td>{{iot.writing_re}}</td> <td>{{iot.attitude}}</td> <td>{{iot.Portfolio}}</td>
             {% endfor %}
         </tr>
         <tr>
             <td div class="pointer"> <i class="fas fa-chalkboard-teacher"></i> 융합 프로젝트 <button type="button" class="btn btn-success">포트폴리오</button>
             </td>
             {% for mix in user.mix_project_set.all %}
             <td>{{mix.performance}}</td> <td>{{mix.performance_re}}</td> <td>{{mix.writing}}</td> <td>{{mix.writing_re}}</td> <td>{{mix.attitude}}</td> <td>{{mix.Portfolio}}</td>
             {% endfor %}
         </tr>
     
        </div>
</div>    
</body>
{% endblock %}

mysite/assessment/templates/assessment/post_home.html
<br>

<div>
&nbsp;&nbsp;&nbsp;<i class="fas fa-highlighter"> 성취도 평가</i>
</div>

<br>
<body>
        
        <div class="table"><table  style="width:100%"> <tr><th>비NCS 교과명</th> <th>수행1</th><th>수행2</th><th>필답1</th><th>필답2</th><th>태도</th><th>포트폴리오</th> </tr>
        <td div class= "pointer"><p style="color:blue;"><i class="fas fa-chalkboard-teacher"></i> 인터페이스 개발</p></td>
         {% for interface in user.interface_set.all %}
         <td>{{interface.performance}}</td> <td>{{interface.performance_re}}</td><td>{{interface.writing}}</td><td>{{interface.writing_re}}</td><td>{{interface.attitude}}</td><td>{{interface.Portfolio}}</td>
         {% endfor %}
         <tr>   
            <td div class="pointer"><p style="color:blue;"><i class="fas fa-chalkboard-teacher"></i>  인터페이스 개발 프로젝트</p> <button type="button" class="btn btn-success">포트폴리오</button>
            </td>{% for interpro in user.interface_project_set.all %}
            <td>{{interpro.performance}}</td> <td>{{interpro.performance_re}}</td><td>{{interpro.writing}}</td><td>{{interpro.writing_re}}</td><td>{{interpro.attitude}}</td><td>{{interpro.Portfolio}}</td>
            {% endfor %}
         </tr>
         <tr>
            <td div class= "pointer"><p style="color:blue;"> <i class="fas fa-chalkboard-teacher"></i> 엣지 디바이스 제어</p></td>
            {% for edge in user.edge_device_set.all %}
            <td>{{edge.performance}}</td> <td>{{edge.performance_re}}</td> <td>{{edge.writing}}</td> <td>{{edge.writing_re}}</td> <td>{{edge.attitude}}</td> <td>{{edge.Portfolio}}</td>
            {% endfor %}
         </tr>   
         <tr>
             <td div class="pointer"><p style="color:blue;"> <i class="fas fa-chalkboard-teacher"></i> 게이트 웨이 디바이스 제어</p></td>
             {% for gateway in user.gateway_device_set.all %}
             <td>{{gateway.performance}}</td> <td>{{gateway.performance_re}}</td> <td>{{gateway.writing}}</td> <td>{{gateway.writing_re}}</td> <td>{{gateway.attitude}}</td> <td>{{gateway.Portfolio}}</td>
             {% endfor %}
         </tr> 
         <tr>
             <td div class="pointer"><p style="color:blue;"> <i class="fas fa-chalkboard-teacher"></i> Iot 프로젝트 </p><button type="button" class="btn btn-success">포트폴리오</button>
             </td>
             {% for iot in user.iot_project_set.all %}
             <td>{{iot.performance}}</td> <td>{{iot.performance_re}}</td> <td>{{iot.writing}}</td> <td>{{iot.writing_re}}</td> <td>{{iot.attitude}}</td> <td>{{iot.Portfolio}}</td>
             {% endfor %}
         </tr>
         <tr>
             <td div class="pointer"> <p style="color:blue;"><i class="fas fa-chalkboard-teacher"></i> 융합 프로젝트 </p><button type="button" class="btn btn-success">포트폴리오</button>
             </td>
             {% for mix in user.mix_project_set.all %}
             <td>{{mix.performance}}</td> <td>{{mix.performance_re}}</td> <td>{{mix.writing}}</td> <td>{{mix.writing_re}}</td> <td>{{mix.attitude}}</td> <td>{{mix.Portfolio}}</td>
             {% endfor %}
         </tr>
     
        </div>
</body>