mysite/blog/urls.py
from django.urls import path, re_path
from blog.views import *
from blog import views


app_name = 'blog'
urlpatterns = [
    path('', PostLV.as_view(), name='index'),

    path('<int:pk>/',PostDV.as_view(), name='detail'),
    #re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),

    #Example : /blog/archive/
    path('archive/', PostAV.as_view(), name='post_archive'),
    
    # Example: /blog/archive/2019/
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    
    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    
    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # Example : /blog/add/
    path('add/', PostCreateView.as_view(), name ='add'),

    # Example :/blog/99/update/
    path('<int:pk>/update/', PostUpdateView.as_view(), name ="update"),

    # Example :/blog/99/delete/
    path('<int:pk>/delete/', PostDeleteView.as_view(), name ="delete"),

    # Example :
    path('download/<int:id>', download, name="download"),
]

mysite/instrouction/urls.py
from django.urls import path
from instrouction.views import InstrouctionLV, InstrouctionDV

app_name ='instrouction'

urlpatterns = [
    path('', InstrouctionLV.as_view(), name='index'), #index는 들어가는걸 담당한다.
    path('list/', InstrouctionDV.as_view(), name ='list'),
    path('list/intro', InstrouctionDV.as_view(), name ='intro'),
    path('list/structure', InstrouctionDV.as_view(), name ='structure'),
    path('list/plan', InstrouctionDV.as_view(), name ='plan'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import  HomeView, UserCreateView, UserCreateDoneTV
from django.urls import path

# from instrouction.views import InstrouctionLV, InstrouctionDV
from mysite.views import HomeView, InstrouctionIntroView, InstrouctionPlanView, InstrouctionStructureView, InstrouctionView, ProfileView

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='home'),
    path('account/', include('django.contrib.auth.urls')), # 로그인, 로그아웃, 비밀번호 변경 등 담당
    
    
    path('account/register/', UserCreateView.as_view(), name='register'), 
    path('account/register/done/', UserCreateDoneTV.as_view(),name='register_done'), # 회원 가입 및 처리
    path('instrouction/',InstrouctionView.as_view(), name='instrouctionbase'),
    path('instrouction/intro',InstrouctionIntroView.as_view(), name ='intro'),
    path('instrouction/structure',InstrouctionStructureView.as_view(), name ='structure'),
    path('instrouction/plan',InstrouctionPlanView.as_view(), name ='plan'),
    path('assessment/', include('assessment.urls')), #평가 url
    path('instrouction/',include('instrouction.urls')),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('blog/',include('blog.urls')),
    path('board/', include('board.urls')),
    path('events/',include('events.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

mysite/instrouction/models.py
from django.db import models

# Create your models here.
# from django.contrib.auth.models import User

class Instrouction(models.Model):
    title = models.CharField('TITLE', max_length =100, blank=True)


    # owner = models.ForeignKey(User, on_delete= models.CASCADE, blank=True, null=True)
    # auth_user에서 상속받는다


    def __str__(self):
        return self.title

mysite/instrouction/views.py
from typing import List
from django.shortcuts import render

# Create your views here.

from django.views.generic import ListView, DetailView
from instrouction.models import Instrouction


class InstrouctionLV(ListView):
    model = Instrouction

class InstrouctionDV(DetailView):
    model = Instrouction
    ## defatul : templates/app_name/model_detail
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # object 만들어낸다.
        context['object_list'] = Instrouction.objects.all()
        return context


# from django.views.generic import CreateView, UpdateView, DeleteView
# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.urls import reverse_lazy
# from mysite.views import OwnerOnlyMixin

# class InstrouctionCreateView(LoginRequiredMixin,CreateView):
#     model = Instrouction
#     fields =['title','contenthead','content'] #생성할 목록들
#     success_url = reverse_lazy('instrouction:index') #완료되면 돌아갈 페이지

#     def form_valid(self,form):   # 타당성 검사
#         form.instance.owner = self.request.user # owner가 user에 있다면
#         return super().form_valid(form)   #조상쪽 가서 타당성 확인해라

# class InstrouctionChangeLV(LoginRequiredMixin,ListView):
#     template_name = 'instrouction/instrouction_change_list.html' #여기서 바꿀거임
#     def get_queryset(self): #쿼리셋 함수를 만들껀데
#         return Instrouction.objects.filter(owner =self.request.user) #로그인한 사용자


# class InstrouctionUpdateView(OwnerOnlyMixin,UpdateView):
#     model = Instrouction
#     field = ['title','contenthead','content']
#     success_url = reverse_lazy('indstrouction:index')

# class InstrouctionDeleteView(OwnerOnlyMixin, DeleteView):
#     model = Instrouction
#     success_url = reverse_lazy('instrouction:index')

mysite/instrouction/templates/instrouction/instrouction_base.html
<h3>훈련소개</h3>
<br>
 <!-- 이 베이스를 고치자 
 훈련개요(링크)
 교과편성 총괄표(링크)
 교과별 계획(링크) -->
<li class ="nav-item mx-1 btn btn-primary" >
        <a class="nav-link text-blue" href ="{% url 'instrouction:intro' %}">훈련개요</a></li>

<br>

<li class ="nav-item mx-1 btn btn-primary" >
        <a class="nav-link text-blue" href ="{% url 'instrouction:structure' %}">교과편성 총괄표</a></li>

<br>

<li class ="nav-item mx-1 btn btn-primary" >
        <a class="nav-link text-blue" href ="{% url 'instrouction:plan' %}">교과별 계획</a></li>

mysite/instrouction/templates/instrouction/instrouction_detail.html
{% extends "base.html" %}

{% block title %}instrouction_detail.html{% endblock %}

    
{% block content %}
<div class ="row">
    <div class = "col-md-2">
        {% include 'instrouction/instrouction_base.html' %}
        
      
    </div>

    <div class = "col-md-10">
        <h3>{{ instrouction.title}}</h3>
            <br>
<pre>
{{ instrouction.contenthead }}

{{ instrouction.content  }}

{{ instrouction.content2 }}

{{ instrouction.content3 }}

{{ instrouction.content4 }}

{{ instrouction.content5 }}

{{ instrouction.content6 }}



    </pre>
            

            

        <a href="{% url 'instrouction:index' %}">목록으로</a>

    </div>
</div>
{% endblock %}

mysite/instrouction/templates/instrouction/instrouction_list.html
{% extends "base.html" %}

{% block title %}instrouction_list.html{% endblock %}

{% block content %}
<div class ="row">
    <div class = "col-md-2">
    <h3>훈련개요</h3>
    <h3>교과편성 총괄표</h3>    
    <h3>교과별 계획</h3>    
    

    </div>

    <div class = "col-md-10">
        <h3>선택하세요</h3>
    </div>
</div>

<!-- <div>
    {% if user.is_active %}
    <a href="#" class="btn btn-primary btn-sm">
    <i class="fas fa-pencil-alt"></i> 쓰기</a>
    <a href="#"
    class="btn btn-primary btn-sm"><i class="far fa-edit"></i> 수정 목록</a>
    {% endif %}
</div> -->

{% endblock %}