mysite/blog/urls.py
from django.urls import path, re_path
from blog.views import *
from blog import views


app_name = 'blog'
urlpatterns = [
    path('', PostLV.as_view(), name='index'),

    path('<int:pk>/',PostDV.as_view(), name='detail'),
    #re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),

    #Example : /blog/archive/
    path('archive/', PostAV.as_view(), name='post_archive'),
    
    # Example: /blog/archive/2019/
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    
    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    
    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # Example : /blog/add/
    path('add/', PostCreateView.as_view(), name ='add'),

    # Example :/blog/99/update/
    path('<int:pk>/update/', PostUpdateView.as_view(), name ="update"),

    # Example :/blog/99/delete/
    path('<int:pk>/delete/', PostDeleteView.as_view(), name ="delete"),

    # Example :
    path('download/<int:id>', download, name="download"),
]

mysite/board/urls.py
from django.urls import path, re_path
from .views import *



app_name = 'board'

urlpatterns = [
    path('', BoardLV.as_view(), name='index'),
    path('<int:pk>/', BoardDV.as_view(), name='detail'),
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('search/', SearchFormView.as_view(), name='search'),
    path('add/', BoardCreateView.as_view(), name='add'),
    path('<int:pk>/update/', BoardUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BoardDeleteView.as_view(), name='delete'),
    path('download/<int:id>', download, name='download'),
    path('comment/<int:id>', BoardDV.as_view(), name="comment"),

    # path('comment/create/question/<int:board_id>/', views.comment_create_question, name='comment_create_question'),
    # path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    # path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
] 

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import  HomeView, UserCreateView, UserCreateDoneTV
from django.urls import path

# from instrouction.views import InstrouctionLV, InstrouctionDV
from mysite.views import HomeView, InstrouctionIntroView, InstrouctionPlanView, InstrouctionStructureView, InstrouctionView, ProfileView

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='home'),
    path('account/', include('django.contrib.auth.urls')), # 로그인, 로그아웃, 비밀번호 변경 등 담당
    
    
    path('account/register/', UserCreateView.as_view(), name='register'), 
    path('account/register/done/', UserCreateDoneTV.as_view(),name='register_done'), # 회원 가입 및 처리
    path('instrouction/',InstrouctionView.as_view(), name='instrouctionbase'),
    path('instrouction/intro',InstrouctionIntroView.as_view(), name ='intro'),
    path('instrouction/structure',InstrouctionStructureView.as_view(), name ='structure'),
    path('instrouction/plan',InstrouctionPlanView.as_view(), name ='plan'),
    path('assessment/', include('assessment.urls')), #평가 url
    path('instrouction/',include('instrouction.urls')),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('blog/',include('blog.urls')),
    path('board/', include('board.urls')),
    path('events/',include('events.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

mysite/board/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField
from taggit.managers import TaggableManager
from account.models import User

# Create your models here.

class Board(models.Model):
    title       = models.CharField(verbose_name='TITLE', max_length=50)
    owner       = models.ForeignKey(User, on_delete=models.CASCADE,
                                verbose_name='OWNER', blank=True, null=True)
    description = models.CharField('DESCRIPTION', max_length=100,
                            blank=True, help_text='simple description text.')
    content     = HTMLField('CONTENTC')                                                    #  models.TextField('CONTENT')
    create_dt   = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt   = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name='OWNER', blank=True, null=True)
    hit         = models.PositiveIntegerField(default=0)
    mainphoto = models.ImageField(upload_to='img/%Y%m%d', blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):              # 현재 데이터의 절대 경로 추출
        return reverse('board:detail', args=(self.id,))

    def get_previous(self):                  # 이전 데이터 추출
        return self.get_previous_by_modify_dt()

    def get_next(self):                      # 다음 데이터 추출
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)




class BoardAttachFile(models.Model):
    board            = models.ForeignKey(Board, on_delete=models.CASCADE,
                                        related_name="files",
                                        verbose_name='Board', blank=True, null=True)
    upload_file     = models.FileField(upload_to="%Y/%m/%d",
                                        null=True, blank=True, verbose_name='파일')
    filename        = models.CharField(max_length=64, null=True,
                                        verbose_name='첨부파일명')
    content_type    = models.CharField(max_length=128, null=True,
                                        verbose_name='MIME TYPE')
    size            = models.IntegerField('파일 크기')


    def __str__(self):
        return self.filename

# 이미지 기능
class Photo(models.Model):
    post = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='img/', blank=True, null=True)

# 댓글 기능
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return (self.author.username if self.author else "무명")+ "의 댓글"


# 게시판 이미지 추가 링크(https://wikidocs.net/91424)
# 댓글 기능 링크 1(https://wikidocs.net/71655)
# 댓글 기능 링크 2(https://fabl1106.github.io/django/2019/05/16/Django-22.-%EC%9E%A5%EA%B3%A0-%EB%8C%93%EA%B8%80-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0(%ED%95%A8%EC%88%98%ED%98%95-%EB%B7%B0).html)

mysite/board/forms.py
from django import forms
from .models import Board, Comment   #, Question, Answer

class BoardForm(forms.Form):
    title = forms.CharField(label = "제목")
    description = forms.CharField(label = "간단 설명")
    content = forms.CharField(label = "내용")
    tags = forms.CharField(label = "Tags")

class BoardSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')
    target = forms.CharField(label='Search Target')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        labels = {
            'text': '댓글내용',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].label = "댓글"

mysite/board/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, TemplateView, FormView, CreateView, UpdateView, DeleteView
from django.db.models import Q, F
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin
from django.http import FileResponse
from .forms import BoardSearchForm, CommentForm    #, QuestionForm, AnswerForm
import os
from django.conf import settings
from .models import Board, BoardAttachFile, Comment
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# ListView
class BoardLV(ListView):
    model = Board
    template_name = 'board/board_index.html'   # 템플릿 파일명 변경
    context_object_name = 'boards'          # 컨텍스트 객체 이름 변경(object_list)
    paginate_by = 5                        # 페이지네이션, 페이지 당 문서 건 수

# DetailView
class BoardDV(DetailView):
    model = Board

#--- Tag View
class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Board

    def get_queryset(self):
        return Board.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

#--- FormView
class SearchFormView(FormView):
    form_class = BoardSearchForm
    template_name = 'board/board_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        board_list = Board.objects.filter(
            Q(title__icontains=searchWord) |
            Q(description__icontains=searchWord) |
            Q(content__icontains=searchWord)
        ).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = board_list

        return render(self.request, self.template_name, context)

class BoardCreateView(LoginRequiredMixin, CreateView):
    model = Board
    fields = ['title', 'description', 'content', 'tags']
    success_url = reverse_lazy('board:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        response = super().form_valid(form)  # Post 모델 저장, self.object

        # 업로드 파일 얻기
        files = self.request.FILES.getlist("files")
        for file in files:
            attach_file = BoardAttachFile(board=self.object, filename = file.name,
                                        size = file.size, content_type = file.content_type,
                                        upload_file = file)
            attach_file.save()

        return response

class BoardUpdateView(OwnerOnlyMixin, UpdateView):
    model = Board
    fields = ['title', 'description', 'content', 'tags']
    success_url = reverse_lazy('board:index')

    def form_valid(self, form):
        delete_files = self.request.POST.getlist("delete_files")
        for fid in delete_files:
            file = BoardAttachFile.objects.get(id=int(fid))
            file_path = os.path.join(settings.MEDIA_ROOT, str(file.upload_file))
            os.remove(file_path)
            file.delete()
            
        response = super().form_valid(form)

        files = self.request.FILES.getlist("files")
        for file in files:
            attach_file = BoardAttachFile(board=self.object,filename = file.name,
            size = file.size, content_type = file.content_type, upload_file = file)
            attach_file.save()
        return response

class BoardDeleteView(OwnerOnlyMixin, DeleteView):
    model = Board
    success_url = reverse_lazy('board:index')


def download(request, id):
    file = BoardAttachFile.objects.get(id=id)
    file_path = os.path.join(settings.MEDIA_ROOT, str(file.upload_file))

    return FileResponse(open(file_path, 'rb'))


def view(request, no=0, page=1):
    # 존재하는 게시글이 없을 경우 return
    if no == 0:
        return HttpResponseRedirect('list')

    board = Board.objects.filter(id=no)

    data = {
        'board':board[0],
        'page':page,
    }

    response = render(request, 'board/board_detail.html', data)
    if request.session.get('authUser') is None:
        cookie_name = 'hit'
    else:
        cookie_name = f'hit:{request.session["authUser"]["id"]}'


    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(no) not in cookies_list:
            board.update(hit=F('hit') + 1)
            return response
    else:
        board.update(hit=F('hit') + 1)
        return response

    return render(request, 'board/board_detail.html', data)



# class CommentCreateView(LoginRequiredMixin, CreateView):
#     @login_required(login_url='mysite:login')
#     def comment_create_question(request, board_id):
#         """
#         board 댓글등록
#         """
#         question = get_object_or_404(Board, pk=board_id)
#         if request.method == "POST":
#             form = CommentForm(request.POST)
#             if form.is_valid():
#                 comment = form.save(commit=False)
#                 comment.author = request.user
#                 comment.create_date = timezone.now()
#                 comment.question = question
#                 comment.save()
#                 return redirect('board:detail', question_id=board_id)
#         else:
#             form = CommentForm()
#         context = {'form': form}
#         return render(request, 'board/comment_form.html', context)


# class CommentUpdateView(OwnerOnlyMixin, UpdateView):
#     @login_required(login_url='mysite:login')
#     def comment_modify_question(request, comment_id):
#         """
#         board 댓글수정
#         """
#         comment = get_object_or_404(Comment, pk=comment_id)
#         if request.user != comment.author:
#             messages.error(request, '댓글수정권한이 없습니다')
#             return redirect('pybo:detail', question_id=comment.question.id)

#         if request.method == "POST":
#             form = CommentForm(request.POST, instance=comment)
#             if form.is_valid():
#                 comment = form.save(commit=False)
#                 comment.author = request.user
#                 comment.modify_date = timezone.now()
#                 comment.save()
#                 return redirect('board:detail', question_id=comment.question.id)
#         else:
#             form = CommentForm(instance=comment)
#         context = {'form': form}
#         return render(request, 'board/comment_form.html', context)

# class CommentDeleteView(OwnerOnlyMixin, DetailView):
#     @login_required(login_url='common:login')
#     def comment_delete_question(request, comment_id):
#         """
#         pybo 질문댓글삭제
#         """
#         comment = get_object_or_404(Comment, pk=comment_id)
#         if request.user != comment.author:
#             messages.error(request, '댓글삭제권한이 없습니다')
#             return redirect('pybo:detail', question_id=comment.question_id)
#         else:
#             comment.delete()
#         return redirect('pybo:detail', question_id=comment.question_id)

mysite/board/templates/board/board_confirm_delete.html
<head>
    <style>
        @font-face {
                font-family: 'Pangolin';
                src: url("font/Pangolin-Regular.ttf") format("opentype");
        }

        body{
            background-image: url('http://v3wall.com/wallpaper/1920_1080/1006/1920_1080_20100605092402139801.jpg');
            background-repeat: no-repeat;
            background-size:cover;
        }

    </style>

</head>
<body>
{% extends "base.html" %}
{% block title %}게시글 삭제하기{% endblock %}
{% block content %}

    <h1>게시글 삭제</h1>
    <br>

    <form action="." method="post">{% csrf_token %}
        <p>정말 "{{ object }}" 을 삭제하시겠습니까?</p>

        <button type="submit"  class="btn btn-success">예</button>
        <button type="button" class="btn btn-success" onclick="location.href = '/board/'">아니오</button>
    </form>

{% endblock %}
</body>

mysite/board/templates/board/board_detail.html
<<<<<<< HEAD
{% extends "base.html" %}
=======
{% extends "base.html" %} 
>>>>>>> e7fae5fc34cdf95b08cf77526ba9354390566d8a
{% load static %}

{% block title %}게시판 내용{% endblock %}
{% block content %}

<h2 style="font-family:Pangolin;">{{object.title}}</h2>

<<<<<<< HEAD
<hr style="border: 5px solid skyblue;width:100%;">

=======

<div class="card" style="margin-left:6%">

<h2 style='margin-top:10px;'>{{object.title}}</h2>

<p style='margin-top:10px;'>
    {%if object.get_previous %}
        <a href="{{object.get_previous.get_absolute_url}}"
            title="이전 글">prev</a>
    {%endif%}

    {%if object.get_next %}
        <a href="{{object.get_next.get_absolute_url}}"
            title="다음 글">next</a>
    {%endif%}
</p>
>>>>>>> e7fae5fc34cdf95b08cf77526ba9354390566d8a
<div class="text-right">작성자: {{board.owner}} / 조회수: {{board.hit}} /
    수정일: {{ board.modify_dt|date:"Y년 m월 d일" }}</div>

<div class="text-right my-3">
    {% for file in board.files.all %}
    <a href="{%url 'board:download' file.id%}" class="ml-4">
        <i class="fas fa-download"></i>
        {{file.filename}} ({{file.size | filesizeformat}}) </a>
    {% endfor %}
</div>
{# <p>{{object.modify_dt | date:"Y-m-d"}}</p> #}
{# <p>작성자: {{object.owner.username}}</p> #}
<br>

<div class = 'mx-auto' style="border: 1px solid black;width: 75%; height:90%;">

    {% if board.mainphoto %}
    <img src ="{{ board.mainphoto.url }}" alt=""height="200">
    <br>
    {% endif %}

    {{board.content | safe}}

</div>
<br>
<br>



<div class="container p-3 my-3 border">

<form action="{ % url "board:comment" object.id % }" method="POST">
    {% csrf_token %}
    
        

    
    </form>
    
    <table class="table table-striped">
        {% for comment in comments %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="{ % url 'board:comment_delete' board.id % }">삭제하기</a></td>
            <td><a href="{ % url 'board:comment_update' board.id % }">수정하기</a></td>
        </tr>
        {% endfor %}
    </table>

</div>

<div>
    <b>TAGS</b> <i class="fas fa-tag"></i>
    {% load taggit_templatetags2_tags %}
    {% get_tags_for_object object as "tags" %}
    {% for tag in tags %}
    <a href="{% url 'board:tagged_object_list' tag.name %}">#{{tag.name}}</a>
    {% endfor %}
    <!-- &emsp;<a href="{% url 'board:tag_cloud' %}">
        <span class="btn btn-info btn-sm">TagCloud</span> </a> -->
</div>
</body>

{% if user == object.owner %}
<div class="text-right">
    <a href="{% url 'board:update' board.id %}" class="mr-3">
        <i class="far fa-edit"></i> 수정</a>
    <a href="{% url 'board:delete' board.id %}" class="text-danger mr-3">
        <i class="fas fa-trash"></i> 삭제</a>
</div>
{% endif %}


<p>
    {%if object.get_previous %}
        <a href="{{object.get_previous.get_absolute_url}}"
            title="이전 글">prev</a>
    {%endif%}

    {%if object.get_next %}
        <a href="{{object.get_next.get_absolute_url}}"
            title="다음 글">next</a>
    {%endif%}
</p>

{% endblock %}

mysite/board/templates/board/board_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}게시글 작성{% endblock %}


{% block content %}

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">
            에러가 난 거 같습니다. 다시 한 번 시도해주세요.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" enctype="multipart/form-data" >{% csrf_token %}
        <label for="files" class="font-weight-bold">제목</label>
        <br>
        <div class="col-sm-8">
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>
<br>
        <label for="files" class="font-weight-bold">간단 설명</label>
        <br>
        <div class="col-sm-8">
            {{ form.description|add_class:"form-control" }}
        </div>
<br>

<div class="form-group row", style="float:right;">
    <label for="files" class="font-weight-bold">첨부 파일: </label>&nbsp;
    <div>
        <input type="file" id="files" name="files" multiple>
    </div>
</div>

<br>

        <label for="files" class="font-weight-bold">내용</label>
        <br>
        <div>
            {{ form.content|add_class:"form-control" }}
        </div>
<br>
    <div class="form-group row">
        {{ form.tags|add_label_class:"font-weight-bold" }}
        <div class="col-sm-4">
            {{ form.tags|add_class:"form-control" }}
        </div>
    </div>


    
    <div class="form-group row">
        <div class="col-sm-8 ">
            {% for file in board.files.all %}
            <input type="checkbox" name="delete_files" value="{{file.id}}">
            {{file.filename}} ({{file.size | filesizeformat}})
            <br>
            {%endfor %}
        </div>
    </div>

<br>

<div class="form-group">
    <div>
        <button type="submit"  class="btn btn-muted">글 등록</button>
        <button type="button" class="btn btn-muted" style = "float:right;" onclick="location.href = '/board/'">돌아가기</button>
    </div>
</div>
</form>


{% endblock %}


{% block extra-script %}
 <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
 referrerpolicy="origin"></script>
 <script>
 tinymce.init({
 selector:'textarea',
 menubar: false,
 statusbar: false,
 toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat'});
</script>
{% endblock %}

<div class="text-right">작성자: {{board.owner}} / 죄회수: {{board.readcount}} /
    수정일: {{ board.modify_dt|date:"Y년 m월 d일" }}</div>

<div class="text-right my-3">
    {% for file in board.files.all %}
    <a href="{%url 'board:download' file.id%}" class="ml-4">
        <i class="fas fa-download"></i>
        {{file.filename}} ({{file.size | filesizeformat}}) </a>
    {% endfor %}
</div>


<div class="text-right">작성자: {{board.owner}} / 죄회수: {{board.read_cnt}} /
    수정일: {{ board.modify_dt|date:"Y년 m월 d일" }}</div>
<div class="form-group row">
    <label for="files" class="col-form-label col-sm-2 ml-3 font-weight-bold">
        삭제할 파일 :</label>
    <div class="col-sm-8 ">
        {% for file in board.files.all %}
        <input type="checkbox" name="delete_files" value="{{file.id}}">
        {{file.filename}} ({{file.size | filesizeformat}})
        <br>
        {%endfor %}
    </div>
</div>
    

mysite/board/templates/board/board_index.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content ="width-device-width, initial-scale=1">
    <title>게시판</title>
    <link rel="stylesheet" href="css/bootstrap.css">
</head>
{% extends "base.html" %}
{% block title %}게시판{% endblock %}

{% block content %}

<style>
    h1{
        position:relative;
        margin-top:20px;
    }

    .table{
        position:relative;
        
    }
    .card{
        position: relative;
        margin-left:30px;
    }
</style>

<div class="card">
<h1>게시판</h1>
<br>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>제목</th>
            <th>작성자</th>
            <th>날짜</th>
            <th>조회수</th>
        </tr>
    </thead>
    <tbody>
        {%for board in boards%}
        <tr>
            <td><a href="{{board.get_absolute_url}}">{{board.title}}</a></td>
            <td>{{board.owner}}</td>
            <td>{{board.create_dt}}</td>
            <td>{{board.hit}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


    {% if user.is_active %}
    <div class="text-right mr-3">
        <a href="{%url 'board:add' %}" class="btn btn-muted btn-sm">
        <i class="fas fa-pencil-alt"></i> 쓰기</a>
    </div>
    {% endif %}



    {% include "pagination.html" %}

</div>


{% endblock %}

mysite/board/templates/board/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content" 
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}