mysite/blog/urls.py
from django.urls import path, re_path
from blog.views import *
from blog import views


app_name = 'blog'
urlpatterns = [
    path('', PostLV.as_view(), name='index'),

    path('<int:pk>/',PostDV.as_view(), name='detail'),
    #re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),

    #Example : /blog/archive/
    path('archive/', PostAV.as_view(), name='post_archive'),
    
    # Example: /blog/archive/2019/
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    
    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    
    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),

    # Example : /blog/add/
    path('add/', PostCreateView.as_view(), name ='add'),

    # Example :/blog/99/update/
    path('<int:pk>/update/', PostUpdateView.as_view(), name ="update"),

    # Example :/blog/99/delete/
    path('<int:pk>/delete/', PostDeleteView.as_view(), name ="delete"),

    # Example :
    path('download/<int:id>', download, name="download"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import  HomeView, UserCreateView, UserCreateDoneTV
from django.urls import path

# from instrouction.views import InstrouctionLV, InstrouctionDV
from mysite.views import HomeView, InstrouctionIntroView, InstrouctionPlanView, InstrouctionStructureView, InstrouctionView, ProfileView

from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='home'),
    path('account/', include('django.contrib.auth.urls')), # 로그인, 로그아웃, 비밀번호 변경 등 담당
    
    
    path('account/register/', UserCreateView.as_view(), name='register'), 
    path('account/register/done/', UserCreateDoneTV.as_view(),name='register_done'), # 회원 가입 및 처리
    path('instrouction/',InstrouctionView.as_view(), name='instrouctionbase'),
    path('instrouction/intro',InstrouctionIntroView.as_view(), name ='intro'),
    path('instrouction/structure',InstrouctionStructureView.as_view(), name ='structure'),
    path('instrouction/plan',InstrouctionPlanView.as_view(), name ='plan'),
    path('assessment/', include('assessment.urls')), #평가 url
    path('instrouction/',include('instrouction.urls')),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('blog/',include('blog.urls')),
    path('board/', include('board.urls')),
    path('events/',include('events.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

mysite/blog/models.py
from django.db import models
from django.urls import reverse

from django.utils.text import slugify
from account.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length =100, blank=True, help_text='simple description text.')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    readcount = models.IntegerField('READCOUNT',blank=True, default= 0)

    owner = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name='OWNER', blank=True, null=True)



    class Meta:
        verbose_name ='post'
        verbose_name_plural ='posts'
        db_table = 'blog_posts' # 테이블명 재정의  실제 table명을 나타냄
        ordering = ('-modify_dt',)    # orderby절, -이면 내림차순  디폴트정렬이며 튜플이라 , 가 있음

    def __str__(self):
        return self.title

    def get_absolute_url(self): # 현재 데이터의 절대 경로 추출
        #return reverse('blog:detail', args=(self.slug,))
        return reverse('blog:detail', args=(self.id,))
    def get_previous(self): # 이전 데이터 추출
        return self.get_previous_by_modify_dt()
    
    def get_next(self): # 다음 데이터 추출
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args,**kwargs)


class PostAttachFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                            related_name="files",
                            verbose_name='Post', blank=True, null=True)
    upload_file = models.FileField(upload_to="%Y/%m/%d",
                            null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True,
                                verbose_name='첨부파일명')
    content_type = models.CharField(max_length=128, null=True,
                                verbose_name='MIME TYPE')
    size = models.IntegerField('파일 크기')
        
    def __str__(self):
        return self.filename

mysite/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label = 'Search Word') # 여긴 필수항목이라고 나옴
    #target = forms.CharField(label = 'Search Target')

mysite/blog/views.py
from django.db import models
from django.shortcuts import render
# Create your views here.

from django.views.generic import ListView, DetailView, TemplateView
from blog.models import Post, PostAttachFile
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

from django.views.generic import FormView
from django.db.models import Q,F
from blog.forms import PostSearchForm

from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin


# ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html' # 템플릿 파일명 변경
    context_object_name = 'object_list' # 컨텍스트 객체 이름 변경(object_list)
    paginate_by = 5 # 페이지네이션, 페이지당 문서 건 수

# DetailView
class PostDV(DetailView):
    model = Post

    def get_context_data(self,**kwargs):
    #     # 조회수 증가기능 # readcount 라는 integer type 추가
            context = super(DetailView,self).get_context_data(**kwargs)
            obj = self.get_object()
            obj.readcount = obj.readcount + 1
            obj.save()
            return context
        
        


#ArchiveView
class PostAV(ArchiveIndexView):
    model=Post
    date_field ='modify_dt'

class PostYAV(YearArchiveView):
    model=Post
    date_field = 'modify_dt'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field ='modify_dt'
    month_format = '%m'

class PostDAV(DayArchiveView):
    model =Post
    date_field = 'modify_dt'
    month_format ='%m'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    month_format = '%m'

#--- Tag View
# class TagCloudTV(TemplateView):
#     template_name = 'taggit/taggit_cloud.html'

# class TaggedObjectLV(ListView):
#     template_name = 'taggit/taggit_post_list.html'
#     model = Post

#     def get_queryset(self):
#         return Post.objects.filter(tags__name=self.kwargs.get('tag'))

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['tagname'] = self.kwargs['tag']
#         return context

# #--- FormView
# class SearchFormView(FormView):
#     form_class = PostSearchForm
#     template_name = 'blog/post_search.html' 

#     def form_valid(self, form):
#         searchWord = form.cleaned_data['search_word']
#         post_list = Post.objects.filter(
#             Q(title__icontains=searchWord) |
#             Q(description__icontains=searchWord) |
#             Q(content__icontains=searchWord)
#         ).distinct()

#         context = {}
#         context['form'] = form
#         context['search_term'] = searchWord
#         context['object_list'] = post_list
#         return render(self.request, self.template_name, context)


# class PostCreateView(LoginRequiredMixin, CreateView):
#     model = Post
#     fields = ['title','slug','descripthon','content','tags']
#     initial = {'slug': 'auto-filling-do-not-input'}
#     success_url = reverse_lazy('blog:index')

#     def form_valid(self, form):
#         form.instance.owner = self.request.user
       
class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description']
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        #form.instance.modify_dt = timezone.now()

        delete_files = self.request.POST.getlist("delete_files")
        for fid in delete_files: # fid는 문자열 타입임
            file = PostAttachFile.objects.get(id=int(fid))
            file_path = os.path.join(settings.MEDIA_ROOT, str(file.upload_file))
            os.remove(file_path) # 실제 파일 삭제
            file.delete() # 모델 삭제(테이블의 행 삭제)

        response = super().form_valid(form)
        files = self.request.FILES.getlist("files")

        for file in files:
            attach_file = PostAttachFile(post= self.object, filename = file.name,
                size = file.size, content_type = file.content_type, upload_file = file)
            attach_file.save()
        return response

class PostDeleteView(OwnerOnlyMixin, DeleteView) :
    model = Post
    success_url = reverse_lazy('home')


from django.http import FileResponse

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'description','readcount']
    success_url = reverse_lazy('home')
 
    def form_valid(self, form):
        form.instance.owner = self.request.user
 
        # return HttpResponseRedirect(self.get_success_url())
        response = super().form_valid(form) # Post 모델 저장, self.object
        
        # 업로드 파일 얻기
        files = self.request.FILES.getlist("files")
        for file in files:
            attach_file = PostAttachFile(post= self.object, filename = file.name,
                                size = file.size, content_type = file.content_type,
                                upload_file = file)
            attach_file.save()
        return response

from django.http import FileResponse
import os
from django.conf import settings

def download(request, id):
    file = PostAttachFile.objects.get(id=id)
    file_path = os.path.join(settings.MEDIA_ROOT, str(file.upload_file))

    return FileResponse(open(file_path, 'rb'))


# from django.http import HttpResponseRedirect
# from account.models import User

# def view(request, no=0, page=1):
#     # 존재하는 게시글이 없을 경우 return
#     if no == 0:
#         return HttpResponseRedirect('list')

#     post = Post.objects.filter(id=no)

#     data = {
#         'post':post[0],
#         'page':page,
#     }

#     response = render(request, 'blog/post_all.html', data)
#     if request.session.get('account_user') is None:
#         cookie_name = 'readcount'
#     else:
#         cookie_name = f'readcount:{request.session["account_user"]["id"]}'


#     if request.COOKIES.get(cookie_name) is not None:
#         cookies = request.COOKIES.get(cookie_name)
#         cookies_list = cookies.split('|')
#         if str(no) not in cookies_list:
#             post.update(hit=F('readcount') + 1)
#             return response
#     else:
#         post.update(hit=F('readcount') + 1)
#         return response

#     return render(request, 'blog/post_all.html', data)

mysite/blog/templates/blog/post_all.html
<style>
   table{font-size:13px;}

</style>
<br>
<h3 >&nbsp;&nbsp;<i class="fas fa-bell">공지사항 </i></h3> 
<br>
    <table class = "table table-hover">
        <thead>
            <tr>
                <th>제목</th>
                <th>작성자</th>
                <th>조회수</th>
                <th>등록일</th>
            </tr>
        </thead>

        <tbody>
            {% for object in object_list %}
            <tr>
                <th><a href='{{ object.get_absolute_url }}' target="_blank">{{ object.title }}</a></th>
                <th>{{object.owner}}</th>  
                <th>{{object.readcount}}</th> 
                <th>{{object.create_dt|date:"Y-n-d" }}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>


<!-- <p>{{ post.description }}</p> -->

{% if user.is_admin %}
<div class="text-right mr-3">
    <a href="{%url 'blog:add' %}" class="btn btn-primary btn-sm">
<i class="fas fa-pencil-alt"></i> 쓰기</a>
</div>
{% endif %}
{% include "pagination.html" %}

mysite/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}

<h1>Post Archives until {% now "b d, Y" %}</h1>

{% for date in date_list %}

<a href="{% url 'blog:post_year_archive' date|date:'Y' %}" class="btn btn-outline-primary btn-sm mx-1">
    Year-{{ date|date:"Y" }}</a>
{% endfor %}

<br><br>
<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mysite/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
<br><br>
<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mysite/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>
<br><br>
<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mysite/blog/templates/blog/post_archive_today.html
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

mysite/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ year|date:"Y" }}</h1>
{% for date in date_list %}
<a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b' %}" class="btn btn-outline-primary btn-sm mx-1">
    {{ date|date:"F" }}</a>
{% endfor %}
<br><br>
<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}
<h1>Post Delete</h1>
<br>
<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
</form>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}

<div style="margin-left:6%">
<h2>{{ object.title }}</h2>


<div>{{ object.modify_dt|date:"Y년 F j일" }}</div>
<p>작성자 : {{object.owner}}</p>
<p>조회수 : {{object.readcount}}</p>
<div class="text-right my-3">
    {% for file in post.files.all %}
    <a href="{%url 'blog:download' file.id%}" class="ml-4">
   <i class="fas fa-download"></i>
    {{file.filename}} ({{file.size | filesizeformat}}) </a>
    {% endfor %}
    </div>

<br>

<div>
    {{ object.description|linebreaks }}
</div>

<p>
    {% if object.get_next %}
    <a href="{{ object.get_next.get_absolute_url }}" title="View previous post">
        <i class="fas fa-arrow-circle-left"></i> 다음 글
    </a>
    {% endif %}

    {% if object.get_previous %}
    | <a href="{{ object.get_previous.get_absolute_url }}" title="View next post">
        이전 글 <i class="fas fa-arrow-circle-right"></i>
    </a>
    {% endif %}
</p>
<ul class="navbar-nav mr-auto">
<li class=" btn">
    <a class="nav-link text-black" href="{% url 'home' %}"></i> 돌아가기</a>
</li>
</ul>

{% if user == object.owner %}
<div class="text-right">
    <a href="{% url 'blog:update' post.id %}" class="mr-3">
        <i class="far fa-edit"></i> 수정</a>
    <a href="{% url 'blog:delete' post.id %}" class="text-danger mr-3">
        <i class="fas fa-trash"></i> 삭제</a>
</div>
{% endif %}
<div>
    {{ post.content | linebreaks}}
</div>
<div>
        {{ post.content | safe }}
</div>
</div>

{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}post_form.html{% endblock %}
{% block content %}
<h1>Post Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your post.</p>
{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">
        Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}
<form action="." method="post" enctype="multipart/form-data" class="card pt-3">{% csrf_token %}
    
    <div class="form-group row">

        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>
    </div>
    <div class="form-group row">
        {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.slug|add_class:"form-control"|attr:"readonly" }}
        </div>
        <small class="form-text text-muted">{{ form.slug.help_text }}</small>
    </div>
    <div class="form-group row">
        {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.description|add_class:"form-control" }}
        </div>
        <small class="form-text text-muted">
            {{ form.description.help_text }}</small>
    </div>
    <div class="form-group row">
        <label for="files"
        class="col-form-label col-sm-2 ml-3 font-weight-bold">첨부 파일 :</label>
        <div class="col-sm-8 ">
        <input type="file" id="files" name="files" multiple>
        </div>
    </div> 
    <div class="form-group row">
        {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-8">
            {{ form.content|add_class:"form-control" }}
        </div>
    </div>
    <div class="form-group row">
        {{ form.tags|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.tags|add_class:"form-control" }}
        </div>
        <small class="form-text text-muted">{{ form.tags.help_text }}</small>
    </div>
    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info" />
        </div>
    </div>
</form>
{% endblock %}


{% block extra-script %}
 <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
 referrerpolicy="origin"></script>
 <script>
 tinymce.init({
 selector:'textarea',
 menubar: false,
 statusbar: false,
 toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat'});
</script>
{% endblock %}

<div class="text-right">작성자: {{post.owner}} / 죄회수: {{post.readcount}} /
    수정일: {{ post.modify_dt|date:"Y년 m월 d일" }}</div>

<div class="text-right my-3">
    {% for file in post.files.all %}
    <a href="{%url 'blog:download' file.id%}" class="ml-4">
        <i class="fas fa-download"></i>
        {{file.filename}} ({{file.size | filesizeformat}}) </a>
    {% endfor %}
</div>


<div class="text-right">작성자: {{post.owner}} / 죄회수: {{post.read_cnt}} /
    수정일: {{ post.modify_dt|date:"Y년 m월 d일" }}</div>
<div class="form-group row">
    <label for="files" class="col-form-label col-sm-2 ml-3 font-weight-bold">
        삭제할 파일 :</label>
    <div class="col-sm-8 ">
        {% for file in post.files.all %}
        <input type="checkbox" name="delete_files" value="{{file.id}}">
        {{file.filename}} ({{file.size | filesizeformat}})
        <br>
        {%endfor %}
    </div>
</div>
    